### PR TITLE
June 21, 2017 meeting

### PR DESCRIPTION
**Pull request by benlesh**

### CODE REVIEW

**Comment by Igorbek** [comment]
Where can be seen the progress of interface types cleanup? Is any issue that tracks all these efforts?

**Comment by kwonoj** [comment]
@Igorbek No there isn't. It'd individual effort have to go through codebases.

**Comment by Igorbek** [comment]
Ah, ok. I thought there had been a discussion regarding these interfaces; wanted to bike shed :)

**Comment by kwonoj** [comment]
@Igorbek It's general high-level discussion - we'd like to limit interface level to not to expose unnecessary implementation details on next major releases.

**Comment by Igorbek** [comment]
that was my first impression when I saw that so many details exposed, like `closed` on `Observer` and `Subscription`.

**Comment by kwonoj** [comment]
If you're interested feel freely create issue on RxJS repo - this repo is probably not feasible place to discuss.

**Pull request merged**
