### PR TITLE
Add 12/20/16 Meeting Notes

### PR DESCRIPTION
**Pull request by jayphelps**

### CODE REVIEW

**Comment by mattpodwysocki** [comment]
@jayphelps did you capture the error trapping strategies that we discussed via [failsafe](https://github.com/jhalterman/failsafe/) anywhere?

**Comment by mattpodwysocki** [comment]
@jayphelps we should also mention not only `join` and `groupJoin`, but also Join Patterns via `Observable.when` with `Observable.prototype.and` and `Observable.prototype.thenDo`

**Comment by jayphelps** [comment]
> @jayphelps did you capture the error trapping strategies that we discussed via failsafe anywhere?

In my personal notes, but I didn't add them here. I'm happy to do so, but it's very early so our plans seemed very vague--don't want to overcommit.

> @jayphelps we should also mention not only join and groupJoin, but also Join Patterns via Observable.when with Observable.prototype.and and Observable.prototype.thenDo

I don't recall discussing that, but I may be been spacing off. Is satisfactory to just change it to something like "Join patterns like join/groupJoin/when/etc"? I don't think it's neccesary to be exhaustive and fear it would overcommit.

**Comment by mattpodwysocki** [comment]
@jayphelps regardless of whether we decide to ship/not ship should be tangental to the discussion having taken place.  It's just good to have notes saying we discussed something in the past regardless of whether we commit to it or not so we don't keep covering the same thing over and over again.

With regards to `Observable.when` being with `join` and `groupJoin`, I'm ok with that.

**Comment by jayphelps** [comment]
@mattpodwysocki I used to feel that way but have gotten pretty paranoid seeing the communities reaction to TC39 proposals--that most people don't realize that just because something is proposed doesn't mean it has a good chance of making it. 🐧

**Comment by mattpodwysocki** [comment]
@jayphelps that's why it's crucial to have that checklist of what's been decided to be in and what's out at this point for any particular milestone so people know what we're accountable for, else the rest is just idle chatter, throwing stuff against the wall to see what sticks.  But if you really feel this way, I'll just make personal notes to make sure I'm not harping on the same things over and over.

**Pull request merged**
