### PR TITLE
docs: fix broken stackoverflow link

### PR DESCRIPTION
**Pull request by JayKan**

### CODE REVIEW

**Comment by jayphelps** [comment]
Thank you! 🎉

**Comment by JayKan** [comment]
@jayphelps,

I'm curious if anybody can join the bi weekly meeting or it's exclusive to only to core members?

Thanks,
Jay

**Comment by jayphelps** [comment]
@JayKan at this time it's invite-only so that we stay on topic and everyone feels comfortable expressing opinions frankly. We also use Google Hangouts which has a limit of 15 users in a session and we wouldn't want invited attendees unable to join.

**Comment by JayKan** [comment]
@jayphelps that's good to know, thanks for your quick reply 👍

**Pull request merged**
